### ISSUE TITLE
Initial tile art

### ISSUE THREAD

**Issue by andrewandrepowell** [Ice-Cream-Team/ProjectMandrill#4]
We're gonna need tile art to start off. The retro sonic games use 16x16 based tiles. We should probably figure out soon whether or not we want to rely on this standard, and then get some basic tiles for our game.

**Comment by TooManyJohns** [comment]
I can do this tomorrow, can just be bland coloring for now as we discussed before.  A 16 bit might be the way to go, I didn't mind the look of them on those games in terms of the final product of the art on them (in which this really comes down to) and the less pixel art I gotta do the better, for everyone!

**Comment by andrewandrepowell** [comment]
When I say 16x16, I'm just referring to the size of each tile lol. We can use any number of colors

**Comment by TooManyJohns** [comment]
Created initial tile art.
