### ISSUE TITLE
Naming and Coding Conventions

### ISSUE THREAD

**Issue by andrewandrepowell** [Ice-Cream-Team/ProjectMandrill#5]
We need to establish some basic conventions when writing our code so it all looks complete. Here are a few proposals...

- Constant values should always be in all caps. I feel like this is a standard across most programming languages.
- Camel-case for Resource names (i.e. Objects, Rooms, Sprites, etc.) and underscore for variable names. The main reason is because this is consistent with Game Maker's naming conventions.

Thoughts?

**Comment by TooManyJohns** [comment]
Yep, totally agree, it's how I handled my last project as well 👍

**Comment by TooManyJohns** [comment]
As talked about on Discord:

**Hungarian Notation + _ + Name of Resource**
When dealing with resources

**Snake Case**
When dealing with variables in code
